name: Cloudflare pages deploy

on:
  push:
    branches:
      - main
    # paths:
    #   - 'apps/frontend/**'

defaults:
  run:
    working-directory: ./apps/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm run pages:deploy --project-name grabbarnagrus
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
